# Generated by Django 4.0 on 2022-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podserver', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_spotify_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
